/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customlist;

import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author Ananthu
 */
public class itemspainter extends javax.swing.JPanel implements ListCellRenderer{

    /**
     * Creates new form items
     */
    
    public itemspainter() {
        initComponents();
//        setForeground(Color.BLACK);
        setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        info = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        selectionLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 5), new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true)));
        setMinimumSize(new java.awt.Dimension(380, 160));
        setPreferredSize(new java.awt.Dimension(380, 160));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/Icon 1/123456.png"))); // NOI18N
        image.setText("image");

        name1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        name1.setText("name");

        info.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        info.setText("info");

        selectionLabel.setText("not-selected");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addGap(74, 74, 74)
                        .addComponent(selectionLabel)
                        .addGap(71, 71, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(name1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(selectionLabel)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image;
    private javax.swing.JLabel info;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel selectionLabel;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @param jlist
     * @param value
     * @param index
     * @param isSelected
     * @param cellHasFocus
     * @return
     */
    @Override
    public Component getListCellRendererComponent(JList jlist, Object value,
            int index, boolean isSelected, boolean cellHasFocus) {
        itemmodel model = (itemmodel) value;
        image.setIcon(model.getIcon());
        name1.setText(model.getName());
        info.setText(model.getInfo());
        
        name1.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent me) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//                System.out.println("Name was clicked");
            }

            @Override
            public void mousePressed(MouseEvent me) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseReleased(MouseEvent me) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseEntered(MouseEvent me) {
                 
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseExited(MouseEvent me) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        if(isSelected){
//            setBackground(Color.LIGHT_GRAY);
setBackground(new Color(217, 219, 218,255));
            setForeground(Color.WHITE);
//            name1.setForeground(Color.WHITE);
//            info.setForeground(Color.WHITE);
//            denyBtn.setForeground(Color.WHITE);
//            acceptBtn.setForeground(Color.WHITE);
        }
        else if(!isSelected){
            setBackground(Color.WHITE);
            setForeground(Color.LIGHT_GRAY);
            name1.setForeground(Color.BLACK);
            info.setForeground(Color.BLACK);
//            denyBtn.setForeground(Color.BLACK);
//            acceptBtn.setForeground(Color.BLACK);
        }else{
//        setBackground(Color.WHITE);
//        setForeground(Color.BLACK);
//        name1.setForeground(Color.BLACK);
//        info.setForeground(Color.BLACK);
//        denyBtn.setForeground(Color.BLACK);
//        acceptBtn.setForeground(Color.BLACK);
        }
        return this;
    }
}
