/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customlist;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;

/**
 *
 * @author Ananthu
 */
public class itemBook extends javax.swing.JPanel {

    /**
     * Creates new form BookPanel
     */
    public itemBook() {
        initComponents();
        setBackground(new Color(252, 239, 139, 50));
        setBorder(new CompoundBorder(new EmptyBorder(10,10,10,10),new LineBorder(Color.BLACK, 1,true)));
        addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent me) {
                    
                }

                @Override
                public void mousePressed(MouseEvent me) {
                }

                @Override
                public void mouseReleased(MouseEvent me) {
                }

                @Override
                public void mouseEntered(MouseEvent me) {
                    setBackground(new Color(204, 204, 204));
                }

                @Override
                public void mouseExited(MouseEvent me) {
                    setBackground(new Color(252, 239, 139, 20));
                }
            });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bookpic = new javax.swing.JLabel();
        bookname = new javax.swing.JLabel();
        bookauthor = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        setLayout(new java.awt.GridBagLayout());

        bookpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/Icon 1/123456.png"))); // NOI18N
        bookpic.setMaximumSize(new java.awt.Dimension(150, 100));
        bookpic.setMinimumSize(new java.awt.Dimension(150, 100));
        bookpic.setPreferredSize(new java.awt.Dimension(700, 450));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -568;
        gridBagConstraints.ipady = -330;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 10);
        add(bookpic, gridBagConstraints);

        bookname.setText("Book name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 89;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 19, 0, 10);
        add(bookname, gridBagConstraints);

        bookauthor.setText("Book Author");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 89;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 19, 0, 10);
        add(bookauthor, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookauthor;
    private javax.swing.JLabel bookname;
    private javax.swing.JLabel bookpic;
    // End of variables declaration//GEN-END:variables
}
