
import customlist.itemBook;
import customlist.itemspainter;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.EmptyBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ananthu
 */
public class bookgridlist extends javax.swing.JFrame {

    /**
     * Creates new form bookgridlist
     */
    public bookgridlist() {
        initComponents();
        
         Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int height = screenSize.height;
        int width = (screenSize.width)*3/4;
        int column = (int)(width/180); 
        int row = 4;
        setSize(width+60,height);
        setLocationRelativeTo(null);
        
//        setContentPane(jPanel1);
        JPanel jPanel =new JPanel(new GridLayout(row, column,3,10));
        jPanel.setBackground(new Color(252, 239, 139, 100));
        jPanel.setSize(width+30,height);
        jPanel.setBorder(new EmptyBorder(10,3,10,10 ));
//        jPanel.setBorder(BorderFactory.createCompoundBorder(new EmptyBorder(5,5,5,10 ), new EmptyBorder(5,5,5,10 )));
        JScrollPane jsp = new JScrollPane(jPanel);
//        jsp.setBorder(new javax.swing.border.LineBorder(null, 2 ));
        jsp.setSize(width+50, height);
//        jsp.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
//        jsp.setViewport();
        jsp.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        jsp.setBorder(new EmptyBorder(10,10,40,10));
        int cellcount = row*column;
        for(int i=0;i<cellcount;i++){
            itemBook item = new itemBook();
            
            jPanel.add(item);
        }
//        bookgridlist item1 = new bookgridlist();
//        bookgridlist item2 = new bookgridlist(); 
//        item1.setSize(getContentPane().getWidth(),100);
//        item2.setSize(getContentPane().getWidth(),100);
//        item1.setLocation(0, 0);
//        item2.setLocation(0,70);
//        jPanel.add(item1);
//        jPanel.add(item2);
        headingPanel.setSize(width+60,100);
        bookslist.setSize(width+60,height);
        bookslist.add(jsp);
        jPanel.setOpaque(false);
        jsp.setOpaque(false);
        
        headingPanel.setBackground(new Color(252, 239, 139, 100));
        jsp.setBackground(new Color(252, 239, 139, 100));
        bookslist.setOpaque(false);
        
//        getContentPane().add(headingPanel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookslist = new javax.swing.JPanel();
        headingPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        statuslabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        javax.swing.GroupLayout bookslistLayout = new javax.swing.GroupLayout(bookslist);
        bookslist.setLayout(bookslistLayout);
        bookslistLayout.setHorizontalGroup(
            bookslistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bookslistLayout.setVerticalGroup(
            bookslistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        getContentPane().add(bookslist);
        bookslist.setBounds(0, 95, 635, 496);

        jLabel1.setFont(new java.awt.Font("Android Insomnia", 3, 48)); // NOI18N
        jLabel1.setText("Books");

        statuslabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout headingPanelLayout = new javax.swing.GroupLayout(headingPanel);
        headingPanel.setLayout(headingPanelLayout);
        headingPanelLayout.setHorizontalGroup(
            headingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(statuslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        headingPanelLayout.setVerticalGroup(
            headingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1))
            .addGroup(headingPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(statuslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(headingPanel);
        headingPanel.setBounds(0, 0, 635, 89);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookgridlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookgridlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookgridlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookgridlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookgridlist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bookslist;
    private javax.swing.JPanel headingPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel statuslabel;
    // End of variables declaration//GEN-END:variables
}
