import java.awt.Canvas;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import project.ConnectionProvider;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ananthu
 */
public class newbook extends javax.swing.JFrame {

    /**
     * Creates new form newbook
     */
    public newbook() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bookprice = new javax.swing.JTextField();
        bookname = new javax.swing.JTextField();
        bookyear = new javax.swing.JTextField();
        shortdesc = new javax.swing.JTextField();
        imagebtn = new javax.swing.JButton();
        bookid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bookauthor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        savebtn = new javax.swing.JButton();
        closebtn = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        longdesc = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 125));
        setUndecorated(true);
        setSize(new java.awt.Dimension(700, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Price");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 50, 26));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("PublishYear");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 80, 26));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Book ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 80, 26));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Short Desc");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 80, 26));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("LongDesc");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 90, 26));

        bookprice.setBackground(new java.awt.Color(255, 255, 153));
        bookprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(bookprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 250, 26));

        bookname.setBackground(new java.awt.Color(255, 255, 153));
        bookname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(bookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 253, 26));

        bookyear.setBackground(new java.awt.Color(255, 255, 153));
        bookyear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bookyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookyearActionPerformed(evt);
            }
        });
        getContentPane().add(bookyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 253, 26));

        shortdesc.setBackground(new java.awt.Color(255, 255, 153));
        shortdesc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(shortdesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 320, 26));

        imagebtn.setBackground(new java.awt.Color(255, 255, 153));
        imagebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        imagebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/Icon 1/uploadimage_copy_30x30.png"))); // NOI18N
        imagebtn.setText("image");
        imagebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagebtnActionPerformed(evt);
            }
        });
        getContentPane().add(imagebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 110, 30));

        bookid.setBackground(new java.awt.Color(255, 255, 153));
        bookid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(bookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 253, 26));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 80, 26));

        bookauthor.setBackground(new java.awt.Color(255, 255, 153));
        bookauthor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bookauthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookauthorActionPerformed(evt);
            }
        });
        getContentPane().add(bookauthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 253, 26));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Author");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 80, 26));

        savebtn.setBackground(new java.awt.Color(255, 255, 153));
        savebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        savebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/Icon 1/save-icon--1.png"))); // NOI18N
        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        getContentPane().add(savebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 100, 31));

        closebtn.setBackground(new java.awt.Color(255, 102, 51));
        closebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/Icon 1/hang_close_copy_60x60.png"))); // NOI18N
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
        });
        getContentPane().add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 60, 60));

        longdesc.setBackground(new java.awt.Color(255, 255, 153));
        longdesc.setColumns(20);
        longdesc.setRows(5);
        jScrollPane1.setViewportView(longdesc);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 320, 110));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/Icon 1/123456.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setMaximumSize(new java.awt.Dimension(738, 450));
        jLabel6.setMinimumSize(new java.awt.Dimension(738, 450));
        jLabel6.setPreferredSize(new java.awt.Dimension(738, 450));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookyearActionPerformed

    private void imagebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagebtnActionPerformed
        // TODO add your handling code here:
        String id = bookprice.getText();
        String name = bookname.getText();
        String publisher = bookyear.getText();
        String price = shortdesc.getText();
        String publishyear = longdesc.getText();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            st.executeUpdate("INSERT INTO book (id,name,publisher,price,publishyear)values("+id+",'"+name+"','"+publisher+"',"+price+",'"+publishyear+"')");
            JOptionPane.showMessageDialog(null,"Insert sucessfull");
            setVisible(false);
            new newbook().setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_imagebtnActionPerformed

    private void bookauthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookauthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookauthorActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savebtnActionPerformed

    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
        // TODO add your handling code here:
                setVisible(false);

    }//GEN-LAST:event_closebtnMouseClicked
  
    
            /**
             * @param args the command line arguments
             */
            public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
                 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                            javax.swing.UIManager.setLookAndFeel(info.getClassName());
                            break;
                        }
                    }
                } catch (ClassNotFoundException ex) {
                    java.util.logging.Logger.getLogger(newbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    java.util.logging.Logger.getLogger(newbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    java.util.logging.Logger.getLogger(newbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                    java.util.logging.Logger.getLogger(newbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new newbook().setVisible(true);
                       }
                });
            }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookauthor;
    private javax.swing.JTextField bookid;
    private javax.swing.JTextField bookname;
    private javax.swing.JTextField bookprice;
    private javax.swing.JTextField bookyear;
    private javax.swing.JLabel closebtn;
    private javax.swing.JButton imagebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea longdesc;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField shortdesc;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JLabel imageJLabel;
}
